sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      # Needed for ARM gcc
      - lib32bz2-1.0
      - lib32ncurses5
      - lib32z1

language: cpp

matrix:
  include:
    - compiler: clang
      env: BUILD_TYPE="tests"
    - compiler: gcc
      env: BUILD_TYPE="tests"
    - compiler: gcc
      env: BUILD_TYPE="build"

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi


install:
  - ci/install.sh

script:
  - ci/build.sh


