dependency-dir: ./src/

depends:
    - serial-datagram:
        fork: Stapelzeiger
    - cmp_mem_access:
        fork: Stapelzeiger
    - cmp:
        fork: cvra

target.arm:
    - src/main.c
    - src/usbcfg.c
    - src/can_driver.c
    - src/can_bridge.c
    - src/uart_bridge.c

source:
    - src/protocol.c
    - src/cmp/cmp.c
    - src/datagram-messages/msg_dispatcher.c
    - src/datagram-messages/service_call.c

include_directories:
    - ./
    - ./src/

templates:
    Makefile.include.jinja: src/src.mk
