dependency-dir: ./src/

depends:
    - serial-datagram:
        fork: Stapelzeiger
    - serial-can-bridge

target.arm:
    - src/board.c
    - src/main.c
    - src/usbcfg.c
    - src/can_driver.c
    - src/can_bridge.c

templates:
    Makefile.include.jinja: src/src.mk
